#!/usr/bin/env bash
#
# Local CI gate: TypeScript types drift check.
#
# The shared TS API types (`parkhub-web/src/api/types.gen.ts`) are
# generated by ts-rs in the parkhub-rust repo and committed into
# parkhub-web for both backends to consume.
#
# The PHP repo cannot regenerate them (no Rust toolchain assumed),
# so this gate is a no-op here. The parkhub-rust repo's pre-push
# hook owns drift detection — see that repo's lefthook.yml.
#
# Kept as a placeholder so the lefthook wiring is uniform across
# both repos: any contributor can read the same script names and
# get a consistent mental model.

set -euo pipefail

echo "PHP repo: types are read-only; parkhub-rust gates type drift."
exit 0
